#!/bin/sh
#Create a new repository on github
#
git init
git add .
git commit -m "first commit"
git remote -v
git remote rm origin
git remote add origin https://github.com/thibau13/Thibault_Asst08.git
git push -u origin master
